version: '3.9'

services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=Crm_syst
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=320330

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backups:/backup
    environment:
      POSTGRES_DB: Crm_syst
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 320330
    restart: unless-stopped


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
